name: Build Cubyz Workflow

run-name: Build Cubyz

on:
  push:
    branches: [ "master", "actions" ]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_linux.sh; echo "probably crashed :)"
        name: Run build script
      # todo: get Cubyz from cache
      # todo: cache zig
      # todo: cache compiler_rt, zig-cache, zig-out
      # todo: split packaging into a separate github artifact/workflow
      - run: file ./zig-out/bin/Cubyzig
      # todo: download a libGL that I upload elsewhere
      # todo: Cubyz-app: change ~ to some root path
      - run: git clone git@github.com:archbirdplus/Cubyz-app.git
      - run: cp ./zig-out/bin/Cubyzig Cubyz-app/Cubyz.app/Contents/MacOS/
      - run: cd Cubyz-app
      # NB: the cd might not carry over if its bash -e 'd
      - run: ./all.sh
      # NB: might need git://path (https://stackoverflow.com/questions/16187849)
      # todo: github-release the app
      
