name: Build Cubyz Workflow

run-name: Build Cubyz

on:
  push:
    branches: [ "master", "actions" ]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run_linux.sh; echo "probably crashed :)"
        name: Run build script
      # todo: get Cubyz from cache
      # todo: cache zig
      # todo: cache compiler_rt, zig-cache, zig-out
      # todo: split packaging into a separate github artifact/workflow
      - run: file ~/zig-out/bin/Cubyzig
      # todo: package into app file, create dmg image
      # todo: github-release the app
      
